accelerator: auto
dataset_class: bracket_brown
dataset_type: mpdd
devices: 1
encoder: resnet18
gradient_clip_val: 25
input: 224
input_size: 256
learning_rate: 0.003
log_dir: ./tb_logs
log_dir_name: exp1
log_every_n_step: 12
max_epochs: 1
momentum: 0.9
num_workers: 0
pretrained: true
test_batch_size: 256
train_batch_size: 6
weight_decay: 3.0e-05
